### Step 01: Import Libraires

In [1]:
import pandas as pd
import numpy as np
import math

import matplotlib as plt
import seaborn as sns

### Step 02: Import CSV files

In [4]:
from src.da_function import load_csv

ModuleNotFoundError: No module named 'src'

In [ ]:
# loan_file_path = './data/input/loan.csv'
# pay_file_path = './data/input/payment.csv'
# var_file_path = './data/input/clarity_underwriting_variables.csv'

# loan_df = pd.read_csv(loan_file_path)
# payment_df = pd.read_csv(pay_file_path)
# variables_df = pd.read_csv(var_file_path, low_memory=False)

# print("Loan DataFrame:", loan_df.shape)
# print("Payment DataFrame:", payment_df.shape)
# print("Variable Descriptions DataFrame:", variables_df.shape)

loan_df, payment_df, variables_df = load_csv()

Loan DataFrame: (577682, 19)
Payment DataFrame: (689364, 9)
Variable Descriptions DataFrame: (49752, 54)

In [8]:
loan_df.head(8)

,loanId,anon_ssn,payFrequency,apr,applicationDate,originated,originatedDate,nPaidOff,approved,isFunded,loanStatus,loanAmount,originallyScheduledPaymentAmount,state,leadType,leadCost,fpStatus,clarityFraudId,hasCF
0,LL-I-07399092,beff4989be82aab4a5b47679216942fd,B,360.00,2016-02-23T17:29:01.940000,False,NaN,0.0,False,0,Withdrawn Application,500.0,978.27,IL,bvMandatory,6,NaN,5669ef78e4b0c9d3936440e6,1
1,LL-I-06644937,464f5d9ae4fa09ece4048d949191865c,B,199.00,2016-01-19T22:07:36.778000,True,2016-01-20T15:49:18.846000,0.0,True,1,Paid Off Loan,3000.0,6395.19,CA,prescreen,0,Checked,569eb3a3e4b096699f685d64,1
2,LL-I-10707532,3c174ae9e2505a5f9ddbff9843281845,B,590.00,2016-08-01T13:51:14.709000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1199.45,MO,bvMandatory,3,NaN,579eab11e4b0d0502870ef2f,1
3,LL-I-02272596,9be6f443bb97db7e95fa0c281d34da91,B,360.00,2015-08-06T23:58:08.880000,False,NaN,0.0,False,0,Withdrawn Application,500.0,1074.05,IL,bvMandatory,3,NaN,555b1e95e4b0f6f11b267c18,1
4,LL-I-09542882,63b5494f60b5c19c827c7b068443752c,B,590.00,2016-06-05T22:31:34.304000,False,NaN,0.0,False,0,Rejected,350.0,814.37,NV,bvMandatory,3,NaN,5754a91be4b0c6a2bf424772,1
5,LL-I-09734486,b5541f49472fa0fce8e473306768f7fb,M,650.00,2016-06-12T19:27:47.951000,False,NaN,0.0,False,0,Withdrawn Application,300.0,738.18,IN,organic,0,NaN,574e2029e4b061d2c3a16a4c,1
6,LL-I-15006968,1828c64bb2dffeae88b27174a9f79ecc,B,680.00,2017-01-12T18:04:37.921000,False,NaN,0.0,False,0,Withdrawn Application,400.0,1362.92,TX,lead,25,NaN,5877c533e4b08f2480ab7e5a,1
7,LL-I-08327946,02596517e7633c7e87e6b333a0fb1bbe,M,449.99,2016-04-01T22:13:02.131000,False,NaN,0.0,False,0,Withdrawn Application,350.0,759.84,UT,bvMandatory,3,NaN,NaN,0

In [9]:
payment_df.head(8)

,loanId,installmentIndex,isCollection,paymentDate,principal,fees,paymentAmount,paymentStatus,paymentReturnCode
0,LL-I-00000021,1,False,2014-12-19T05:00:00,22.33,147.28,169.61,Checked,NaN
1,LL-I-00000021,2,False,2015-01-02T05:00:00,26.44,143.17,169.61,Checked,NaN
2,LL-I-00000021,3,False,2015-01-16T05:00:00,31.30,138.31,169.61,Checked,NaN
3,LL-I-00000021,4,False,2015-01-30T05:00:00,37.07,132.54,169.61,Checked,NaN
4,LL-I-00000021,5,False,2015-02-13T05:00:00,43.89,125.72,169.61,Checked,NaN
5,LL-I-00000021,6,False,2015-02-27T05:00:00,51.97,117.64,169.61,Checked,NaN
6,LL-I-00000021,7,False,2015-03-13T04:00:00,61.54,108.07,169.61,Checked,NaN
7,LL-I-00000021,8,False,2015-03-27T04:00:00,72.87,96.74,169.61,Checked,NaN

### Step 03: Data Transformation

- Functions

In [ ]:
from src.da_function import convert_to_datetime
from src.da_function import rename_columns_by_last_dot
from src.da_function import join_loan_tables

In [ ]:
# # Convert columns containing 'date' in their name to datetime format
# def convert_to_datetime(df):
#     for column_name in df.columns:
#         if 'date' in column_name.lower():
#             df[column_name] = pd.to_datetime(df[column_name], errors='coerce')
#     return df

# # Extract text after the last dot and rename columns
# def rename_columns_by_last_dot(df):
#     df.columns = df.columns.str.split('.').str[-1]
#     return df

# # Merge loan_df and variables_df on the specified keys
# def join_loan_tables(df1, df2):
#     merged_df = pd.merge(
#             df1, 
#             df2, 
#             left_on='anon_ssn', 
#             right_on='underwritingid',
#             how='left',
#             validate='many_to_one'
#         )
#     return merged_df

- Call function

In [ ]:
loan_df = convert_to_datetime(loan_df)
payment_df = convert_to_datetime(payment_df)
variables_df = rename_columns_by_last_dot(variables_df)

# call function to merge tables
loan_detail_df = join_loan_tables(loan_df, variables_df)

### Step 04: EDA (Exploratery Data Analysis)